modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/SilentChaos512/Silent-Gear/issues"
displayURL="https://minecraft.curseforge.com/projects/silent-gear"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512"

[[mods]]
    modId="silentgear"
    version="${file.jarVersion}"
    displayName="Silent Gear"
    #updateJSONURL="http://myurl.me/"
    description='''
    Modular and upgradeable tools, weapons, and armor. Allows full customization of parts used in gear crafting, even user-defined parts!
    '''

[[dependencies.silentgear]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgear]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"
