modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/SilentChaos512/Silent-Gear/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silent-gear"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512"

[[mods]]
    modId="silentgear"
    version="${file.jarVersion}"
    displayName="Silent Gear"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Silent-Gear/1.15/update.json"
    description='''
    Modular and upgradeable tools, weapons, and armor. Allows full customization of parts used in gear crafting, even user-defined parts!
    '''

[[dependencies.silentgear]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgear]]
    modId="silentlib"
    mandatory=true
    versionRange="[4.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgear]]
    modId="silentgems"
    mandatory=false
    versionRange="[3.5.4,)"
    ordering="NONE"
    side="BOTH"
